export const ENV = {
  VITE_APIKEY: 'VITE_APIKEY',
  VITE_AUTHDOMAIN: 'VITE_AUTHDOMAIN',
  VITE_PROJECTID: 'VITE_PROJECTID',
  VITE_STORAGEBUCKET: 'VITE_STORAGEBUCKET',
  VITE_MESSAGESENDERID: 'VITE_MESSAGESENDERID',
  VITE_APPID: 'VITE_APPID',
  VITE_GOOGLEAPI: 'VITE_GOOGLEAPI',
  VITE_GEMINI: 'VITE_GEMINI',
} as const;

export type ENV = keyof typeof ENV;
